site_name: Boxy
site_url: https://boxy.wiki
nav:
  - Home:
    - index.md
  - RenderObjects:
      - render-objects/introduction-to-layout.md
      - render-objects/box-constraints.md
      - render-objects/the-many-trees.md
      - render-objects/interactive-example.md
      - render-objects/learn-mode.md
  - CustomBoxy:
      - custom-boxy/introduction-to-customboxy.md
      - custom-boxy/hello-world.md
      - custom-boxy/boxy-child.md
      - custom-boxy/boxy-id.md
      - custom-boxy/painting.md
      - custom-boxy/layers.md
      - custom-boxy/widget-inflation.md
      - custom-boxy/example-square-layout.md
      - custom-boxy/example-evenly-sized-row.md
      - custom-boxy/example-product-tile.md
  - Flex:
      - flex/cross-axis-alignment.md
      - flex/dominant.md
  - Slivers:
      - slivers/sliver-container.md
      - slivers/sliver-card.md
theme:
  name: material
  custom_dir: overrides
  # logo: assets/puro_icon_small.png
  # favicon: assets/puro_icon_small.png
  palette:
    - scheme: slate
      primary: pink
      accent: pink
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
    - scheme: default
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
  features:
    - navigation.tabs
    - navigation.instant
    - toc.follow
    - content.code.annotate
markdown_extensions:
  - tables
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
extra:
  generator: false
  social:
    - icon: fontawesome/solid/heart
      link: https://tst.sh
repo_url: https://github.com/PixelToast/boxy
extra_css:
  - stylesheets/extra.css
